import type { Question, CategoryInfo } from '../types';

export const categories: CategoryInfo[] = [
  {
    id: 'risk',
    title: 'סובלנות סיכון',
    description: 'נבין כמה סיכון מתאים לך',
    icon: '⚖️',
    required: true,
  },
  {
    id: 'experience',
    title: 'ניסיון וידע',
    description: 'נבדוק את הרקע שלך בהשקעות',
    icon: '📚',
    required: true,
  },
  {
    id: 'goals',
    title: 'מטרות השקעה',
    description: 'מה אתה רוצה להשיג?',
    icon: '🎯',
    required: true,
  },
  {
    id: 'behavior',
    title: 'דפוסי התנהגות',
    description: 'איך אתה מתנהג בשוק?',
    icon: '🧠',
    required: true,
  },
  {
    id: 'demographic',
    title: 'קצת עליך',
    description: 'מידע אישי שיעזור לנו להתאים לך תוכן - אופציונלי לחלוטין',
    icon: '👤',
    required: false,
  },
  {
    id: 'financial',
    title: 'מצב כלכלי',
    description: 'הבנת המצב הפיננסי שלך - אופציונלי לחלוטין',
    icon: '💰',
    required: false,
  },
  {
    id: 'personality',
    title: 'אישיות וסגנון',
    description: 'איך אתה מקבל החלטות ולומד - אופציונלי לחלוטין',
    icon: '🎭',
    required: false,
  },
  {
    id: 'motivation',
    title: 'מוטיבציה והקשר',
    description: 'מה הביא אותך לכאן - אופציונלי לחלוטין',
    icon: '💡',
    required: false,
  },
  {
    id: 'open_ai',
    title: 'שאלה פתוחה',
    description: 'ספר לנו במילים שלך',
    icon: '✍️',
    required: true,
  },
];

export const questions: Question[] = [
  // === קטגוריה 1: סובלנות סיכון (risk) ===
  {
    id: 'risk_investment_portion',
    text: 'כמה מהחיסכון שלך היית מוכן/ה להשקיע?',
    type: 'single',
    category: 'risk',
    required: true,
    weight: 3,
    options: [
      { id: 'r1_1', text: 'עד 10% - רק מה שאני מוכן להפסיד', value: 1 },
      { id: 'r1_2', text: '10-25% - חלק קטן מהחסכונות', value: 2 },
      { id: 'r1_3', text: '25-50% - חלק משמעותי', value: 3 },
      { id: 'r1_4', text: '50-75% - רוב החסכונות', value: 4 },
      { id: 'r1_5', text: 'מעל 75% - כמעט הכל', value: 5 },
    ],
  },
  {
    id: 'risk_loss_reaction',
    text: 'איך היית מגיב/ה אם ההשקעה שלך יורדת 20% בשבוע?',
    type: 'single',
    category: 'risk',
    required: true,
    weight: 3,
    options: [
      { id: 'r2_1', text: 'מוכר/ת מיד - לא מוכן להפסיד יותר', value: 1 },
      { id: 'r2_2', text: 'מודאג/ת מאוד, שוקל/ת למכור', value: 2 },
      { id: 'r2_3', text: 'ממתין/ה ורואה מה קורה', value: 3 },
      { id: 'r2_4', text: 'לא מודאג/ת, זה חלק מהמשחק', value: 4 },
      { id: 'r2_5', text: 'קונה עוד! מחירים נמוכים = הזדמנות', value: 5 },
    ],
  },
  {
    id: 'risk_comfort_level',
    text: 'באיזו רמת סיכון את/ה מרגיש/ה בנוח?',
    type: 'scale',
    category: 'risk',
    required: true,
    weight: 2,
    minScale: 1,
    maxScale: 10,
    scaleLabels: { min: 'שמרני מאוד', max: 'אוהב/ת סיכון' },
  },

  // === קטגוריה 2: ניסיון וידע (experience) ===
  {
    id: 'exp_previous',
    text: 'האם יש לך ניסיון קודם בהשקעות?',
    type: 'single',
    category: 'experience',
    required: true,
    weight: 2,
    options: [
      { id: 'e1_1', text: 'אין לי ניסיון כלל', value: 1 },
      { id: 'e1_2', text: 'קראתי על זה אבל לא השקעתי', value: 2 },
      { id: 'e1_3', text: 'השקעתי קצת בעבר', value: 3 },
      { id: 'e1_4', text: 'משקיע/ה באופן קבוע כמה שנים', value: 4 },
      { id: 'e1_5', text: 'משקיע/ה מנוסה עם ניסיון רב', value: 5 },
    ],
  },
  {
    id: 'exp_concepts',
    text: 'אילו מושגים מוכרים לך?',
    type: 'multiple',
    category: 'experience',
    required: true,
    weight: 2,
    options: [
      { id: 'e2_1', text: 'מניות', value: 1 },
      { id: 'e2_2', text: 'אגרות חוב', value: 1 },
      { id: 'e2_3', text: 'קרנות נאמנות / ETF', value: 1 },
      { id: 'e2_4', text: 'קריפטו', value: 1 },
      { id: 'e2_5', text: 'נדל"ן להשקעה', value: 1 },
      { id: 'e2_6', text: 'אופציות ונגזרים', value: 1 },
    ],
  },
  {
    id: 'exp_learning_source',
    text: 'מאיפה את/ה לומד/ת על השקעות היום?',
    type: 'multiple',
    category: 'experience',
    required: true,
    weight: 1,
    options: [
      { id: 'e3_1', text: 'רשתות חברתיות (טיקטוק, אינסטגרם)', value: 1 },
      { id: 'e3_2', text: 'יוטיוב', value: 1 },
      { id: 'e3_3', text: 'ספרים ומאמרים', value: 1 },
      { id: 'e3_4', text: 'חברים ומשפחה', value: 1 },
      { id: 'e3_5', text: 'קורסים מקצועיים', value: 1 },
      { id: 'e3_6', text: 'לא לומד/ת כרגע', value: 0 },
    ],
  },

  // === קטגוריה 3: מטרות (goals) ===
  {
    id: 'goals_main',
    text: 'מה המטרה העיקרית שלך בהשקעות?',
    type: 'single',
    category: 'goals',
    required: true,
    weight: 2,
    options: [
      { id: 'g1_1', text: 'חיסכון לפנסיה', value: 1 },
      { id: 'g1_2', text: 'הכנסה פסיבית שוטפת', value: 3 },
      { id: 'g1_3', text: 'חיסכון לרכישת דירה', value: 2 },
      { id: 'g1_4', text: 'חופש כלכלי / עצמאות פיננסית', value: 4 },
      { id: 'g1_5', text: 'ללמוד ולהבין את העולם הפיננסי', value: 2 },
    ],
  },
  {
    id: 'goals_horizon',
    text: 'מה אופק ההשקעה שלך?',
    type: 'single',
    category: 'goals',
    required: true,
    weight: 2,
    options: [
      { id: 'g2_1', text: 'עד שנה', value: 1 },
      { id: 'g2_2', text: '1-3 שנים', value: 2 },
      { id: 'g2_3', text: '3-5 שנים', value: 3 },
      { id: 'g2_4', text: '5-10 שנים', value: 4 },
      { id: 'g2_5', text: 'מעל 10 שנים', value: 5 },
    ],
  },

  // === קטגוריה 4: התנהגות (behavior) ===
  {
    id: 'behavior_check_frequency',
    text: 'כמה פעמים בשבוע אתה בודק/ת את ההשקעות שלך?',
    type: 'single',
    category: 'behavior',
    required: true,
    weight: 1,
    options: [
      { id: 'b1_1', text: 'אף פעם / לא רלוונטי', value: 1 },
      { id: 'b1_2', text: 'פעם בשבוע', value: 2 },
      { id: 'b1_3', text: 'כמה פעמים בשבוע', value: 3 },
      { id: 'b1_4', text: 'כל יום', value: 4 },
      { id: 'b1_5', text: 'כמה פעמים ביום', value: 5 },
    ],
  },
  {
    id: 'behavior_trigger',
    text: 'מה גורם לך לקנות או למכור השקעה?',
    type: 'single',
    category: 'behavior',
    required: true,
    weight: 1,
    options: [
      { id: 'b2_1', text: 'המלצה של מישהו שאני סומך עליו', value: 2 },
      { id: 'b2_2', text: 'מחקר אישי מעמיק', value: 3 },
      { id: 'b2_3', text: 'תחושת בטן', value: 4 },
      { id: 'b2_4', text: 'טרנד / מה שכולם עושים', value: 5 },
      { id: 'b2_5', text: 'אני לא יודע/ת עדיין', value: 1 },
    ],
  },

  // === קטגוריה 5: דמוגרפי (demographic) - אופציונלי ===
  {
    id: 'demo_age',
    text: 'בן/בת כמה את/ה?',
    type: 'single',
    category: 'demographic',
    required: false,
    weight: 0,
    options: [
      { id: 'd1_1', text: '18-24', value: 1 },
      { id: 'd1_2', text: '25-34', value: 2 },
      { id: 'd1_3', text: '35-44', value: 3 },
      { id: 'd1_4', text: '45-54', value: 4 },
      { id: 'd1_5', text: '55+', value: 5 },
    ],
  },
  {
    id: 'demo_family',
    text: 'מה המצב המשפחתי שלך?',
    type: 'single',
    category: 'demographic',
    required: false,
    weight: 0,
    options: [
      { id: 'd2_1', text: 'רווק/ה', value: 1 },
      { id: 'd2_2', text: 'בזוגיות', value: 2 },
      { id: 'd2_3', text: 'נשוי/אה', value: 3 },
      { id: 'd2_4', text: 'נשוי/אה עם ילדים', value: 4 },
    ],
  },
  {
    id: 'demo_education',
    text: 'מה רמת ההשכלה שלך?',
    type: 'single',
    category: 'demographic',
    required: false,
    weight: 0,
    options: [
      { id: 'd3_1', text: 'תיכונית', value: 1 },
      { id: 'd3_2', text: 'תואר ראשון', value: 2 },
      { id: 'd3_3', text: 'תואר שני ומעלה', value: 3 },
      { id: 'd3_4', text: 'אחר', value: 0 },
    ],
  },
  {
    id: 'demo_occupation',
    text: 'מה תחום העיסוק שלך?',
    type: 'single',
    category: 'demographic',
    required: false,
    weight: 0,
    options: [
      { id: 'd4_1', text: 'הייטק', value: 1 },
      { id: 'd4_2', text: 'פיננסים ובנקאות', value: 2 },
      { id: 'd4_3', text: 'חינוך', value: 3 },
      { id: 'd4_4', text: 'בריאות', value: 4 },
      { id: 'd4_5', text: 'עצמאי/ת', value: 5 },
      { id: 'd4_6', text: 'סטודנט/ית', value: 6 },
      { id: 'd4_7', text: 'אחר', value: 0 },
    ],
  },

  // === קטגוריה 6: מצב כלכלי (financial) - אופציונלי ===
  {
    id: 'fin_income',
    text: 'מה טווח ההכנסה החודשית שלך (ברוטו)?',
    type: 'single',
    category: 'financial',
    required: false,
    weight: 0,
    options: [
      { id: 'f1_1', text: 'עד 7,000 ₪', value: 1 },
      { id: 'f1_2', text: '7,000 - 12,000 ₪', value: 2 },
      { id: 'f1_3', text: '12,000 - 20,000 ₪', value: 3 },
      { id: 'f1_4', text: '20,000 - 35,000 ₪', value: 4 },
      { id: 'f1_5', text: 'מעל 35,000 ₪', value: 5 },
    ],
  },
  {
    id: 'fin_savings',
    text: 'האם יש לך חסכונות קיימים?',
    type: 'single',
    category: 'financial',
    required: false,
    weight: 0,
    options: [
      { id: 'f2_1', text: 'אין חסכונות', value: 1 },
      { id: 'f2_2', text: 'עד 50,000 ₪', value: 2 },
      { id: 'f2_3', text: '50,000 - 200,000 ₪', value: 3 },
      { id: 'f2_4', text: 'מעל 200,000 ₪', value: 4 },
    ],
  },
  {
    id: 'fin_debt',
    text: 'האם יש לך חובות או הלוואות פעילים?',
    type: 'single',
    category: 'financial',
    required: false,
    weight: 0,
    options: [
      { id: 'f3_1', text: 'לא, אין לי חובות', value: 1 },
      { id: 'f3_2', text: 'משכנתא בלבד', value: 2 },
      { id: 'f3_3', text: 'הלוואות', value: 3 },
      { id: 'f3_4', text: 'חובות בכרטיסי אשראי', value: 4 },
      { id: 'f3_5', text: 'כמה מהנ"ל', value: 5 },
    ],
  },
  {
    id: 'fin_monthly_remainder',
    text: 'כמה מההכנסה שלך נשאר בסוף החודש?',
    type: 'single',
    category: 'financial',
    required: false,
    weight: 0,
    options: [
      { id: 'f4_1', text: 'לא נשאר - אני במינוס', value: 1 },
      { id: 'f4_2', text: 'מעט מאוד', value: 2 },
      { id: 'f4_3', text: 'סכום סביר שאני יכול לחסוך', value: 3 },
      { id: 'f4_4', text: 'הרבה - אני חוסך באופן קבוע', value: 4 },
    ],
  },

  // === קטגוריה 7: אישיות וסגנון (personality) - אופציונלי ===
  {
    id: 'pers_decision_making',
    text: 'איך את/ה מקבל/ת החלטות גדולות בחיים?',
    type: 'single',
    category: 'personality',
    required: false,
    weight: 0,
    options: [
      { id: 'p1_1', text: 'לפי אינטואיציה ותחושת בטן', value: 1 },
      { id: 'p1_2', text: 'מחקר מעמיק ואיסוף נתונים', value: 2 },
      { id: 'p1_3', text: 'התייעצות עם אנשים שאני סומך עליהם', value: 3 },
      { id: 'p1_4', text: 'שילוב של מחקר, התייעצות ותחושה', value: 4 },
    ],
  },
  {
    id: 'pers_patience',
    text: 'מה רמת הסבלנות שלך כשדברים לא הולכים כמתוכנן?',
    type: 'scale',
    category: 'personality',
    required: false,
    weight: 0,
    minScale: 1,
    maxScale: 10,
    scaleLabels: { min: 'חסר/ת סבלנות', max: 'סבלני/ת מאוד' },
  },
  {
    id: 'pers_financial_stress',
    text: 'איך את/ה מגיב/ה ללחץ כלכלי?',
    type: 'single',
    category: 'personality',
    required: false,
    weight: 0,
    options: [
      { id: 'p3_1', text: 'חרדה ודאגה רבה', value: 1 },
      { id: 'p3_2', text: 'ניתוח רציונלי של המצב', value: 2 },
      { id: 'p3_3', text: 'התעלמות ותקווה שיעבור', value: 3 },
      { id: 'p3_4', text: 'פנייה לעזרה מקצועית', value: 4 },
    ],
  },
  {
    id: 'pers_learning_style',
    text: 'איך את/ה מעדיפ/ה ללמוד דברים חדשים?',
    type: 'single',
    category: 'personality',
    required: false,
    weight: 0,
    options: [
      { id: 'p4_1', text: 'קריאת מאמרים וספרים', value: 1 },
      { id: 'p4_2', text: 'צפייה בסרטונים', value: 2 },
      { id: 'p4_3', text: 'תרגול מעשי - ללמוד תוך כדי עשייה', value: 3 },
      { id: 'p4_4', text: 'שיחות ולמידה מאנשים אחרים', value: 4 },
    ],
  },

  // === קטגוריה 8: מוטיבציה והקשר (motivation) - אופציונלי ===
  {
    id: 'mot_reason',
    text: 'מה הביא אותך לאפליקציה הזו?',
    type: 'single',
    category: 'motivation',
    required: false,
    weight: 0,
    options: [
      { id: 'm1_1', text: 'רוצה להתחיל להשקיע ולא יודע/ת מאיפה', value: 1 },
      { id: 'm1_2', text: 'כבר משקיע/ה ורוצה ללמוד עוד', value: 2 },
      { id: 'm1_3', text: 'חבר/ה המליץ/ה', value: 3 },
      { id: 'm1_4', text: 'סקרנות כללית', value: 4 },
    ],
  },
  {
    id: 'mot_fear',
    text: 'מה הדבר שהכי מפחיד אותך בנושא כסף והשקעות?',
    type: 'single',
    category: 'motivation',
    required: false,
    weight: 0,
    options: [
      { id: 'm2_1', text: 'פחד מהפסד כספי', value: 1 },
      { id: 'm2_2', text: 'חוסר ידע - אני לא מבין/ה מספיק', value: 2 },
      { id: 'm2_3', text: 'לא יודע/ת במי לבטוח', value: 3 },
      { id: 'm2_4', text: 'אין לי מספיק כסף להשקיע', value: 4 },
    ],
  },
  {
    id: 'mot_influence',
    text: 'מי השפיע עליך בנושא כסף?',
    type: 'multiple',
    category: 'motivation',
    required: false,
    weight: 0,
    options: [
      { id: 'm3_1', text: 'הורים ומשפחה', value: 1 },
      { id: 'm3_2', text: 'חברים', value: 1 },
      { id: 'm3_3', text: 'רשתות חברתיות ויוצרי תוכן', value: 1 },
      { id: 'm3_4', text: 'ספרים ופודקאסטים', value: 1 },
      { id: 'm3_5', text: 'אף אחד - אני לומד לבד', value: 0 },
    ],
  },
  {
    id: 'mot_future_feeling',
    text: 'מה היית רוצה להרגיש לגבי הכסף שלך בעוד שנה?',
    type: 'open',
    category: 'motivation',
    required: false,
    weight: 0,
    placeholder: 'ספר/י לנו במילים שלך...',
  },

  // === קטגוריה 9: שאלה פתוחה (open_ai) ===
  {
    id: 'open_ai_goals',
    text: 'איך אתה רוצה להתקדם בעזרת האפליקציה בהשקעות שלך?',
    type: 'open',
    category: 'open_ai',
    required: true,
    weight: 0,
    placeholder: 'ספר/י לנו על הציפיות, המטרות, והחלומות שלך בנושא השקעות...',
  },
];

export function getQuestionsByCategory(category: string): Question[] {
  return questions.filter((q) => q.category === category);
}
